# Dependencies

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            mstengel
tagline:          'Mitteilsame Spur im Netz'
description:      'Engineer, JW, Minimalist'
url:              blog.stngl.net
baseurl:          http://blog.stngl.net/

author:
  name:           'Martin Stengel'
  url:            http://blog.stngl.net

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mstengel/blog
