# Dependencies

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            mstengel
tagline:          'Engineer, JW, Minimalist '
description:      'Mitteilsame Spur im Netz'
url:              blog.stngl.net
baseurl:          /

author:
  name:           'Martin Stengel'
  url:            http://blog.stngl.net

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mstengel/blog
